### ISSUE TITLE
npy文件

### ISSUE THREAD

**Issue by hz-ants** [sjtuytc/segmentation-driven-pose#1]
1.老师：您好！数据集中的xx.npy文件是如何生成的？在本程序中虽然是官方提供，但您可否介绍一下这是如何制作？
2.segmentation-driven-pose与您betapose相比，有没有做过对比？精度与速度？
3.pretrained model.

Occluded-LINEMOD: https://1drv.ms/u/s!ApOY_gOHw8hLbbdmVZgnqk30I5A

YCB-Video: https://1drv.ms/u/s!ApOY_gOHw8hLbLl4i8CAXD6LGuU这两个预训练模型能否发一份给我，因为我用了vpn也无法下载
谢谢！祝愉快！我邮箱：hzcisco@126.com

**Comment by zhanghuihuiwei** [comment]
Hello, I am sorry to disturb you：
1 about your npy:Is this your keypoints？If Yes,different imgs should have different keypoints,but there is one linemod_bbox.npy.
2 about your train.py: How to train the LINEMOD-OCC model?
Thanks a lot!

**Comment by sjtuytc** [comment]
1) the keypoints are from original github repo, so please refer to that for help. Deriving them is not difficult.
2) Linemod is not designed for deep learning , so I didn't reproduce that. But it should be straight forward.
