### ISSUE TITLE
Generation of YCB_bbox.npy and YCB_vertex.npy files

### ISSUE THREAD

**Issue by madhumilan** [sjtuytc/segmentation-driven-pose#13]
Hi,

Thanks for such a neat and self-explanatory code. I would like to use your code for my personal project. I am trying to generate a dataset similar to YCB-V to suit your codebase. I came across ground-truth files like **YCB_bbox.npy** and **YCB_vertex.npy** under data/ folder. Could you please explain me how to generate this or where to obtain this from? It would be really helpful for my current task. Thank you.

Best regards,
Madhu

**Comment by sjtuytc** [comment]
YCB bbox is just to generate the bounding boxes of YCB objects, and the latter is sampled YCB vertices.
