### ISSUE TITLE
ground-truth generation for ycb_dataset.py

### ISSUE THREAD

**Issue by ll-II** [sjtuytc/segmentation-driven-pose#2]
Hello,

I think there might be a problem with the synthetic data generation:
ycb_dataset.py, function gen_synthetic, from line 147:

![Screenshot 2019-11-09 at 14 43 55](https://user-images.githubusercontent.com/22396666/68529498-b718e700-02ff-11ea-8f7d-e4e18b4b945b.png)

In my case the class_mask was not correctly generated:
- class_ids was a list of list of class numbers, like:  [[3, 16,  20, 6]]
 - cid[0] always 3, leading to several errors

I used this code to generate the keypoint with the function 'gen_kp_gt'

I could fix the issue by changing  l. 147 and l. 151  :  

class_ids = meta['cls_indexes'][0]  
class_mask = np.where(seg_label == cid)

**Comment by sjtuytc** [comment]
I'm confused, can you provide a visualization to explain why it's wrong?

**Comment by sjtuytc** [comment]
Feel free to reopen it if necessary.
