### ISSUE TITLE
License is wrong

### ISSUE THREAD

**Issue by user-vm** [sjtuytc/segmentation-driven-pose#3]
This repo contains code from https://github.com/cvlab-epfl/segmentation-driven-pose , which is GPL-3.0. Since it is a requirement of the GPL-3.0 license that all derivative works use the same GPL-3.0 license, this code cannot be released under the MIT license that you have used.
This is also stated under "Conditions" at the top of the https://github.com/cvlab-epfl/segmentation-driven-pose/blob/master/LICENSE page.

**Comment by sjtuytc** [comment]
Thanks, I have fixed that.
