### ISSUE TITLE
The ground-truth semantic labels

### ISSUE THREAD

**Issue by mrchen229** [sjtuytc/segmentation-driven-pose#6]
Hello, in section 3.2 of the paper:"We can therefore generate the ground-truth semantic labels by projecting the 3d models in the images while taking into account the the depth of each object to handle occlusions." this sentence has some doubts, I didn't find relevant codes in your project,Can you give me some help?Thank you very much.

**Comment by sjtuytc** [comment]
pls ask the authors of original paper.
