### ISSUE TITLE
 how to train?what do i need to prepare?

### ISSUE THREAD

**Issue by ameliamlz** [sjtuytc/segmentation-driven-pose#7]
hi,I have some question about training,expect your reply
1.when i running your code,show some problems such as no such file or directory './model/exp007.pth' od '' or 'keyframe_txt'. how to solve it?
2.whether you only code the train.py on ycb-video?
3.what do i need if i want to train on  occluded-LINEMOD? 
thank you very much!

**Comment by sjtuytc** [comment]
run train.py
yes
only need to config paths.
