### ISSUE TITLE
Ground-truth for kp_gt_x &kp_gt_y

### ISSUE THREAD

**Issue by lilixj** [sjtuytc/segmentation-driven-pose#9]
Hi, Could you explain the details of bb8_2d? A little confused with generating the ground truth.

>      
        meta = loadmat(item + '-meta.mat')
        class_ids = meta['cls_indexes']
        with open(in_pkl, 'rb') as f:
            bb8_2d = pickle.load(f)
        for i, cid in enumerate(class_ids):
            class_mask = np.where(seg_label == cid[0])
            kp_gt_map_x[class_mask] = bb8_2d[:,:,0][i]
            kp_gt_map_y[class_mask] = bb8_2d[:,:,1][i]

Thank you!

**Comment by sjtuytc** [comment]
which part are you confusing? it's the x and y coordinates for the bboxes.
